package dev.kafka.kafkautils.gui;

import java.util.Map;

/**
 * Russian display text for module and setting names shown in the ClickGUI.
 * Deliberately separate from {@code Module.getName()}/{@code Setting.getName()}:
 * those strings are also used as config/HUD-position keys (see
 * {@code ConfigManager}, {@code HudManager}), so changing them directly would
 * reset everyone's already-saved settings. This map only affects what's drawn
 * on screen; lookups miss safely by returning the original English text.
 */
final class RuLabels {
   private static final Map<String, String> LABELS = Map.ofEntries(
      // Module names
      Map.entry("Anti Spam", "Антиспам"),
      Map.entry("Auto Teleport", "Авто-телепорт"),
      Map.entry("Chat Ping", "Пинг в чате"),
      Map.entry("Clickable Chat", "Кликабельный чат"),
      Map.entry("Coordinate Share", "Обмен координатами"),
      Map.entry("Economy Tracker", "Учёт экономики"),
      Map.entry("Friend Chat", "Чат друзей"),
      Map.entry("Friend Highlight", "Подсветка друзей"),
      Map.entry("Friend List", "Список друзей"),
      Map.entry("Mod Radar", "Радар мода"),
      Map.entry("Player Logger", "Лог игроков"),
      Map.entry("Player Tracker", "Трекер игроков"),
      Map.entry("Private Messages", "Личные сообщения"),
      Map.entry("Staff List", "Список админов"),
      Map.entry("Staff Notify", "Уведомление об админах"),
      Map.entry("Armor Alert", "Оповещение о броне"),
      Map.entry("Auto Eat", "Авто-еда"),
      Map.entry("Auto Mine", "Авто-майнинг"),
      Map.entry("Auto Pot", "Авто-зелье"),
      Map.entry("Auto Raid", "Авто-рейд"),
      Map.entry("Auto Repair", "Авто-ремонт"),
      Map.entry("Auto Replant", "Авто-пересадка"),
      Map.entry("Auto Shield", "Авто-щит"),
      Map.entry("Brew Helper", "Помощник варки"),
      Map.entry("DPS Meter", "Счётчик урона"),
      Map.entry("Enchant Helper", "Помощник чар"),
      Map.entry("Enemy Status", "Статус врага"),
      Map.entry("Fast Break", "Быстрый снос"),
      Map.entry("Fast Eat", "Быстрая еда"),
      Map.entry("Fast Swap", "Быстрая замена"),
      Map.entry("Gapple Count", "Счётчик галок"),
      Map.entry("K/D Tracker", "Трекер K/D"),
      Map.entry("Mace Alert", "Оповещение о булаве"),
      Map.entry("Pearl Tracker", "Трекер жемчуга"),
      Map.entry("Pot Heal", "Зелье-лечение"),
      Map.entry("PvP Logger", "PvP-лог"),
      Map.entry("Quick Pearl", "Быстрый жемчуг"),
      Map.entry("Self Durability", "Своя прочность"),
      Map.entry("Splash Predictor", "Прогноз зелья"),
      Map.entry("Totem Counter", "Счётчик тотемов"),
      Map.entry("Active Mods", "Активные модули"),
      Map.entry("Armor Durability ESP", "ESP прочности брони"),
      Map.entry("Economy HUD", "HUD экономики"),
      Map.entry("Effect Logger", "Лог эффектов"),
      Map.entry("Friend Overlay", "Оверлей друзей"),
      Map.entry("Health ESP", "ESP здоровья"),
      Map.entry("Inventory Viewer", "Просмотр инвентаря"),
      Map.entry("Item ESP", "ESP предметов"),
      Map.entry("Messenger Unread", "Непрочитанные (мессенджер)"),
      Map.entry("Ominous Vault ESP", "ESP зловещих хранилищ"),
      Map.entry("Pinned Order", "Закреплённый порядок"),
      Map.entry("Player Inspect", "Осмотр игрока"),
      Map.entry("My Effects", "Мои эффекты"),
      Map.entry("Trial Spawner ESP", "ESP спавнера испытаний"),
      Map.entry("Vanish ESP", "ESP невидимок"),

      // Setting names (shared across modules where the same word is reused)
      Map.entry("Players", "Игроки"),
      Map.entry("Accept Command", "Команда принятия"),
      Map.entry("Keywords", "Ключевые слова"),
      Map.entry("Words", "Слова"),
      Map.entry("Sound", "Звук"),
      Map.entry("Highlight", "Подсветка"),
      Map.entry("Reply on Whisper", "Ответ на личку"),
      Map.entry("Clickable Commands", "Кликабельные команды"),
      Map.entry("Run Commands", "Команды по клику"),
      Map.entry("Prefix", "Префикс"),
      Map.entry("Include Dimension", "Включать измерение"),
      Map.entry("Currency", "Валюта"),
      Map.entry("Chat Notify", "Уведомление в чат"),
      Map.entry("Msg Command", "Команда /msg"),
      Map.entry("Plain Marker", "Простая метка"),
      Map.entry("Accent", "Акцент"),
      Map.entry("Friends", "Друзья"),
      Map.entry("Server URL", "Адрес сервера"),
      Map.entry("Key", "Ключ"),
      Map.entry("Fallback via /msg", "Резерв через /msg"),
      Map.entry("Tab Badge", "Значок в табе"),
      Map.entry("Handshake", "Рукопожатие"),
      Map.entry("Announce", "Оповещение"),
      Map.entry("Ignore NPCs", "Игнорировать NPC"),
      Map.entry("Nicks", "Ники"),
      Map.entry("Incoming Regex", "Regex входящих"),
      Map.entry("Outgoing Regex", "Regex исходящих"),
      Map.entry("Pretty Render", "Красивый вид"),
      Map.entry("Unread HUD", "HUD непрочитанных"),
      Map.entry("Threshold %", "Порог %"),
      Map.entry("Show in HUD", "Показывать в HUD"),
      Map.entry("Chat Alert", "Оповещение в чат"),
      Map.entry("Eat Below", "Есть при"),
      Map.entry("Foods", "Еда"),
      Map.entry("Mode", "Режим"),
      Map.entry("Fast Place", "Быстрая установка"),
      Map.entry("Break Speed", "Скорость ломки"),
      Map.entry("Auto Swap Pickaxe", "Авто-смена кирки"),
      Map.entry("Swap Threshold %", "Порог смены %"),
      Map.entry("Auto Refill Offhand", "Авто-пополнение доп.руки"),
      Map.entry("Auto Drop", "Авто-сброс"),
      Map.entry("Drop Items", "Сбрасывать предметы"),
      Map.entry("Fortune Only", "Только с Удачей"),
      Map.entry("No Swing", "Без замаха"),
      Map.entry("AntiCheat Delay", "Задержка от античита"),
      Map.entry("Target Ores", "Целевая руда"),
      Map.entry("Throw Potion", "Бросковое зелье"),
      Map.entry("Offensive Potions", "Атакующие зелья"),
      Map.entry("Renew After Raid", "Обновлять после рейда"),
      Map.entry("Keep Bad Omen", "Сохранять предзнаменование"),
      Map.entry("Repair Below %", "Чинить при %"),
      Map.entry("Click Interval", "Интервал клика"),
      Map.entry("Only Mending", "Только с Починкой"),
      Map.entry("Rotations", "Повороты"),
      Map.entry("Replant", "Пересадка"),
      Map.entry("Auto Tool (Fortune)", "Авто-инструмент (Удача)"),
      Map.entry("Harvest Tool", "Инструмент сбора"),
      Map.entry("Range", "Радиус"),
      Map.entry("Speed", "Скорость"),
      Map.entry("Crops", "Культуры"),
      Map.entry("Projectile Range", "Радиус снарядов"),
      Map.entry("Block Melee", "Блок ближнего боя"),
      Map.entry("Hold Ticks", "Тиков удержания"),
      Map.entry("Max Cost/Step", "Макс. цена/шаг"),
      Map.entry("Wanted", "Нужное"),
      Map.entry("Min Height", "Мин. высота"),
      Map.entry("Detection Range", "Радиус обнаружения"),
      Map.entry("Show Damage Est", "Показывать оценку урона"),
      Map.entry("Cooldown (s)", "Перезарядка (с)"),
      Map.entry("Show Cooldowns", "Показывать перезарядку"),
      Map.entry("Chat Log", "Лог в чат"),
      Map.entry("Heal Below HP", "Лечить при ХП"),
      Map.entry("Heal Potion", "Зелье лечения"),
      Map.entry("Cooldown Ticks", "Тиков перезарядки"),
      Map.entry("Heal At Feet", "Лечить под ноги"),
      Map.entry("Log Potions/Apples", "Лог зелий/яблок"),
      Map.entry("Log Totem Pops", "Лог срабатываний тотема"),
      Map.entry("PvP Only", "Только PvP"),
      Map.entry("Ominous", "Зловещие"),
      Map.entry("Normal", "Обычные"),
      Map.entry("Enchants", "Чары"),
      Map.entry("Compact ench", "Компакт. чары"),
      Map.entry("Hands", "Руки"),
      Map.entry("Effects", "Эффекты")
   );

   private RuLabels() {
   }

   /** Russian text for {@code english} if known, otherwise the original string unchanged. */
   static String of(String english) {
      if (english == null) {
         return "";
      }
      return LABELS.getOrDefault(english, english);
   }
}
